!-------------------------------------------------------
!
! FACF_FFT: calculate Flux Autocorrelation Function via FFT
!
! By Yanlei Wang,@THU,Mar 2013
! The input file is 'tc.log', which is generated by LAMMPS(run flux.in)
! There are two output files: '0facf.data' and '1nor_facf.data'
!-------------------------------------------------------
program facf_fft
  use, intrinsic :: iso_c_binding
  include 'fftw3.f03'
  
  INTEGER :: nsteps,l,m,k,initstep
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: heat,heat_cent,z,acov,mask,adj,acorr0,acorr,nor_acorr
  DOUBLE COMPLEX,DIMENSION(:),ALLOCATABLE :: out
  DOUBLE PRECISION :: mean,x,y,norm,time,tag
  TYPE(C_PTR) :: plan_f,plan_inv,plan_m,datain1,datain2,dataout1,dataout2,datain_m,dataout_m
 ! REAL(C_DOUBLE),POINTER :: in_m(:)
  COMPLEX(C_DOUBLE_COMPLEX),POINTER :: in1(:),out1(:),in2(:),in_m(:),out_m(:),out2(:)
     
  initstep = 696
  !--------------------------------------------
  ! preparing read,and obtain nsteps&natoms
  !--------------------------------------------
  OPEN (11,FILE='tc.log',STATUS='OLD')
  OPEN (12,FILE='0facf.data',STATUS='UNKNOWN')
  OPEN (13,FILE='1nor_facf.data',STATUS='UNKNOWN')
  !find the nextpow2
  m=0
  nsteps = 7500001
  l = 2*nsteps-1
  k=1
  do while( k .LT. l)
    k=2*k
    m=m+1
  end do
  l=1
  do i=1,m
   l=2*l
  end do
 write(*,*) l 
  !---------------------------------------------
  ! allocate data from dump file
  !---------------------------------------------
  ALLOCATE(heat(nsteps,3),acov(nsteps,3))
  allocate(acorr(nsteps,3),acorr0(nsteps,3),nor_acorr(nsteps,3))
  datain1=fftw_alloc_complex(INT(l,C_SIZE_T))
  dataout1=fftw_alloc_complex(INT(l,C_SIZE_T))
  datain2=fftw_alloc_complex(INT(l,C_SIZE_T))
  dataout2=fftw_alloc_complex(INT(l,C_SIZE_T))
  datain_m=fftw_alloc_complex(INT(l,C_SIZE_T))
  dataout_m=fftw_alloc_complex(INT(l,C_SIZE_T))  
    
  CALL c_f_pointer(datain1,in1,[l])
  CALL c_f_pointer(dataout1,out1,[l])
  CALL c_f_pointer(datain2,in2,[l])
  CALL c_f_pointer(dataout2,out2,[l])
  CALL c_f_pointer(datain_m,in_m,[l])
  CALL c_f_pointer(dataout_m,out_m,[l])  
  !--------------------------------------------
  ! read data from dump file
  !--------------------------------------------
  REWIND(11)
  do i=1,initstep
   read(11,*)
  end do
  READ (11,*)
  DO i = 1, nsteps
    READ (11,*) time,heat(i,:)
  END DO
  CLOSE(11)  
  !--------------------------------------------
  ! calculate Flux Autocorrelation Function
  !--------------------------------------------
  !calculate the mean of flux heat
 write(*,*) 1
  !creat new array

do j=1,3
  do i=1,nsteps
    in1(i) = heat(i,j)
  end do
  do i=nsteps+1,l
    in1(i) = 0
  end do

  write(*,*) 2
  !forward FFT
! plan_f = fftw_plan_dft_r2c_1d(l,in1,out1, FFTW_ESTIMATE)
! call fftw_execute_dft_r2c(plan_f,in1,out1)  
 plan_f= fftw_plan_dft_1d(l,in1,out1,-1,FFTW_ESTIMATE)
 call fftw_execute_dft(plan_f,in1,out1)
write(*,*) 3  
  do i=1,l
    in2(i) = out1(i)
  end do  
  
write(*,*) 4  
  do i=1,l
    x=real(in2(i))
    y=aimag(in2(i))
    norm=x*x+y*y
    in2(i) = norm
  end do
write(*,*) in2(2)
write(*,*) 5  
  !Inverse FFT
!  plan_inv = fftw_plan_dft_c2r_1d(l,in2,out2, FFTW_ESTIMATE)
!  call fftw_execute_dft_c2r(plan_inv,in2,out2)
 plan_inv = fftw_plan_dft_1d(l,in2,out2,+1,FFTW_ESTIMATE)
 call fftw_execute_dft(plan_inv,in2,out2)
write(*,*) 5.5 
write(*,*) aimag(out2(2)) 
  do i=1,l
    acov(i,j) = real(out2(i))/l
  end do
end do
  !=====================================
  !adjust
  !=====================================
!  do i=1,nsteps-1
!    acorr0(i) = acov(l-nsteps+2+i-1) 
!  end do
!  acorr0(nsteps)=acov(1)
!write(*,*) acov(nsteps)
 do j=1,3
 do i=1,nsteps
   acorr(i,j) = acov(i,j)
 end do
 end do
  !======================================
  !normalization
  !======================================
do j=1,3 
 nor_acorr(1,j) = acorr(1,j)/DBLE(nsteps)
  do i=2,nsteps
    nor_acorr(i,j) = (acorr(i,j)/DBLE(nsteps+1-i))/nor_acorr(1,j)
  end do
  nor_acorr(1,j)=1.d0
end do

do j=1,3
  do i=1,nsteps
    acorr(i,j) = acorr(i,j)/DBLE(nsteps+1-i)
  end do  
end do
  !--------------------------------------------
  ! export
  !--------------------------------------------
write(*,*) 8 
  !export the autocorrelation function
  write(12,*) "nsteps"
  write(12,*) nsteps
  
  do i=1,nsteps
    write(12,'(I10,3F20.5)') i,acorr(i,1),acorr(i,2),acorr(i,3)
  end do
  close(12)
  
  do i=1,nsteps
    write(13,'(I10,3F20.5)') i,nor_acorr(i,1),nor_acorr(i,2),nor_acorr(i,3)
  end do
  close(13) 
 end program facf_fft
